language: emacs-lisp
before_install:
  - curl -fsSkL https://gist.githubusercontent.com/rejeep/7736123/raw | sh
  - export PATH="$HOME/.cask/bin:$PATH"
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm install $EVM_EMACS --use
  - emacs --version
  - cask
env:
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.3-bin
script:
  - make install test install-file-with-deps-from-marmalade install-file-with-deps-from-melpa