language: emacs-lisp
before_install:
  # evm install
  - sudo mkdir /usr/local/evm
  - sudo chown travis:travis /usr/local/evm
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"
  - export PATH="$HOME/.cask/bin:$PATH"
  - evm install emacs-24.3-bin
  - evm install $EVM_EMACS --use --force
  - emacs --version
  # cask install
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - cask
env:
  - EVM_EMACS=emacs-24.1-bin
  - EVM_EMACS=emacs-24.2-bin
  - EVM_EMACS=emacs-24.3-bin
script:
  - pwd
  - make install
  - make test
  - make install-file-with-deps-from-marmalade
  - make install-file-with-deps-from-melpa